networks:
  jellyfleet:
    attachable: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.147.0/24
          ip_range: 192.168.147.0/24
          gateway: 192.168.147.254
          # aux_addresses:
          #   traefik: 192.168.147.69
          #   gluetun: 192.168.147.70
          #   jellyfin: 192.168.147.71
            
          #   sonarr: 192.168.147.4
          #   radarr: 192.168.147.5

volumes:
  config:  # Pending rename to `jellyfin-config`
  cache:  # Pending rename to `jellyfin-cache`
  jellyseerr-config:
  sonarr-config:
  radarr-config:
  lidarr-config:
  prowlarr-config:
  qbittorrent-config:
  bazarr-config:
  # transmission-config:

services:
  traefik:
    image: traefik:v3.1
    restart: always
    networks:
      jellyfleet:
        ipv4_address: 192.168.147.1

    # command:
    #   - "--api.insecure=true"
    #   - "--api.debug=true"
    #   - "--log=true"
    #   - "--log.level=DEBUG"
    #   - "--providers.docker=true"
    #   - "--entrypoints.web.address=:80"
    #   - "--entrypoints.websecure.address=:443"
    #   - "--tls.certificates.address=:443"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
      - "${CERTIFICATE_DIRECTORY}:/certs"
      # - .acme.json:/acme.json

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    networks:
      jellyfleet:
        ipv4_address: 192.168.147.2

    ports:
      - "8096:8096"
    user: 1000:1000
    group_add:
      - "989"
    volumes:
      - "config:/config"
      - "cache:/cache"
      - "${MEDIA_DIRECTORY}:/media"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card0
    environment:
      - TZ=${TZ}
      # - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}  # Include protocol prefix (e.g. `https://)
      # - HEALTHCHECK_URL=http://localhost:80/health  # Change the server's jellyfleet port to 8096 here or to 80 in /config/config/network.xml
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${ROOT_FQDN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
  gluetun:
    image: qmcgaw/gluetun:latest
    restart: always
    networks:
      jellyfleet:
        ipv4_address: 192.168.147.3
    # port forwarding for jellyseerr
    ports:
      - "5055:5055"
    cap_add:
      - NET_ADMIN
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS}
      # - DNS_KEEP_NAMESERVER=on
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      # - OPENVPN_CIPHERS=AES-256-GCMk
      # - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      # - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      # - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      # - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      # - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      # - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    restart: always
    network_mode: "service:gluetun"

    depends_on:
      gluetun:
        condition: service_healthy
      jellyfin:
        condition: service_healthy
      sonarr:
        condition: service_healthy
      radarr:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=${TZ}
    volumes:
      - "jellyseerr-config:/app/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.${ROOT_FQDN}`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls=true"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: always
    network_mode: "service:gluetun"

    depends_on:
      gluetun:
        condition: service_healthy
      jellyfin:
        condition: service_healthy
      sonarr:
        condition: service_healthy
      radarr:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=${TZ}
    # volumes:
    #   - "flaresolverr-config:/app/config"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
    #   - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.${ROOT_FQDN}`)"
    #   - "traefik.http.routers.flaresolverr.entrypoints=websecure"
    #   - "traefik.http.routers.flaresolverr.tls=true"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: always
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "prowlarr-config:/config"

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${ROOT_FQDN}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: always
    network_mode: "service:gluetun"
    depends_on:
      prowlarr:
        condition: service_started
      gluetun:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "sonarr-config:/config"
      - "${MEDIA_DIRECTORY}/shows:/shows"
      - "${MEDIA_DIRECTORY}/anime:/anime"
      - "${DOWNLOADS_DIRECTORY}:/downloads"
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
      interval: 20s
      retries: 5
      start_period: 7s
      timeout: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${ROOT_FQDN}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: always
    network_mode: "service:gluetun"
    depends_on:
      prowlarr:
        condition: service_started
      gluetun:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "radarr-config:/config"
      - "${MEDIA_DIRECTORY}/movies:/movies"
      - "${DOWNLOADS_DIRECTORY}:/downloads"
    healthcheck:
      test: curl --fail http://localhost:7878 || exit 1
      interval: 20s
      retries: 5
      start_period: 7s
      timeout: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${ROOT_FQDN}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    restart: always
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "lidarr-config:/config"
      - "${MEDIA_DIRECTORY}/music:/music"
      - "${DOWNLOADS_DIRECTORY}:/downloads"
    healthcheck:
      test: curl --fail http://localhost:8686 || exit 1
      interval: 20s
      retries: 5
      start_period: 7s
      timeout: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.${ROOT_FQDN}`)"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls=true"

  # Bazarr is used to download and categorize subtitles
  # https://www.bazarr.media/
  bazarr:
    image: lscr.io/linuxserver/bazarr
    restart: always
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DIRECTORY}/movies:/movies
      - ${MEDIA_DIRECTORY}/shows:/shows
      - ${MEDIA_DIRECTORY}/anime:/anime
      - "bazarr-config:/config"

    healthcheck:
      test: curl --fail http://localhost:6767 || exit 1
      interval: 20s
      retries: 5
      start_period: 7s
      timeout: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.${ROOT_FQDN}`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"




  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    restart: always
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${DOWNLOADS_DIRECTORY}:/downloads"
      - "qbittorrent-config:/config"

    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 20s
      retries: 5
      start_period: 10s
      timeout: 10s

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbittorrent.rule=Host(`torrent.${ROOT_FQDN}`)"
      # - "traefik.http.routers.qbittorrent.rule=Host(`torrent.int`)"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls=true"

