networks:
  backbone-network:
    name: backbone-network
    external: true

services:
  quartz:
    image: shommey/dockerized-quartz:${QUARTZ_VERSION:-latest}
    container_name: quartz
    restart: unless-stopped
    networks:
      - backbone-network
    volumes:
      - ./obsidian-notes:/vault
    environment:
      TZ: ${TZ}
      REBUILD_WEBHOOK_SECRET: ${QUARTZ_REBUILD_WEBHOOK_SECRET}
      NOTIFY_TARGET: gotify://gotify/${GOTIFY_NOTIFY_TARGET}
      VAULT_DO_GIT_PULL_ON_UPDATE: true
    labels:
      meta.name: "quartz"
      meta.stack: ${STACK}
      traefik.enable: "true"
      traefik.http.services.quartz.loadbalancer.server.port: "80"
      traefik.http.routers.quartz.rule: "Host(`quartz.${ROOT_FQDN}`)"
      traefik.http.routers.quartz.entrypoints: "websecure"
      traefik.http.routers.quartz.tls: "true"
      traefik.http.routers.quartz.service: "quartz"
      traefik.http.routers.quartz.middlewares: "authelia@docker"
      glance.name: Quartz
      glance.icon: /assets/obsidian.svg
      glance.url: https://quartz.${ROOT_FQDN}
      glance.description: Notes
