server:
  port: 8080
  assets-path: /app/assets
theme:
  background-color: 232 23 18
  contrast-multiplier: 1.2
  primary-color: 220 83 75
  positive-color: 105 48 72
  negative-color: 351 74 73
pages:
  !include: home.yml
  !include: feeds.yml
  !include: server.yml