networks:
  backbone-network:
    name: ${BACKBONE_STACK}
    external: true

volumes:
  gotify_data:
  portainer_data:
  uptime_kuma_data:
  beszel_data:

services:
  # gotify:
  #   image: gotify/server:2.6.1
  #   container_name: 'gotify'
  #   restart: unless-stopped
  #   networks:
  #   - backbone-network
  #   # volumes:
  #     # - gotify_data:/app/data
  #     # - ./gotify/config.yml:/etc/gotify/config.yml
  #     # todo
  #   environment:
  #     GOTIFY_DATABASE_DIALECT: postgres
  #     GOTIFY_DATABASE_CONNECTION: '${GOTIFY_DATABASE_CONNECTION}'
  #     GOTIFY_DEFAULTUSER_NAME: ${ADMIN_USER}
  #     GOTIFY_DEFAULTUSER_PASS: ${ADMIN_PASS}
  #     TZ: ${TZ}
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:80/health"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 5s
  #   labels:
  #     meta.name: 'gotify'
  #     meta.stack: ${STACK}
  #     traefik.enable: 'true'
  #     traefik.http.services.gotify.loadbalancer.server.port: '80'
  #     traefik.http.routers.gotify.rule: 'Host(`gotify.${ROOT_FQDN}`)'
  #     traefik.http.routers.gotify.entrypoints: 'websecure'
  #     traefik.http.routers.gotify.tls: 'true'
  #     glance.name: Gotify
  #     glance.icon: /assets/gotify.svg
  #     glance.url: https://gotify.${ROOT_FQDN}
  #     glance.description: Notifications

  # portainer:
  #   image: portainer/portainer-ce:2.24.0-alpine
  #   container_name: 'portainer'
  #   restart: unless-stopped
  #   networks:
  #   - backbone-network
  #   volumes:
  #   - portainer_data:/data
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     TZ: ${TZ}
  #   labels:
  #     meta.name: 'portainer'
  #     meta.stack: ${STACK}
  #     traefik.enable: 'true'
  #     traefik.http.services.portainer.loadbalancer.server.port: '9000'
  #     traefik.http.routers.portainer.rule: 'Host(`portainer.${ROOT_FQDN}`)'
  #     traefik.http.routers.portainer.entrypoints: 'websecure'
  #     traefik.http.routers.portainer.tls: 'true'
  #     glance.name: Portainer
  #     glance.icon: /assets/portainer.svg
  #     glance.url: https://portainer.${ROOT_FQDN}
  #     glance.description: Docker Management

  # uptime-kuma:
  #   image: louislam/uptime-kuma:latest
  #   container_name: 'kuma'
  #   restart: unless-stopped
  #   volumes:
  #     - uptime_kuma_data:/app/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #   - backbone-network
  #   environment:
  #     TZ: ${TZ}
  #     HOST:
  #   labels:
  #     meta.name: 'uptime-kuma'
  #     meta.stack: ${STACK}
  #     traefik.enable: 'true'
  #     traefik.http.services.kuma.loadbalancer.server.port: '3001'
  #     traefik.http.routers.kuma.rule: 'Host(`kuma.${ROOT_FQDN}`)'
  #     traefik.http.routers.kuma.entrypoints: 'websecure'
  #     traefik.http.routers.kuma.tls: 'true'
  #     traefik.http.routers.kuma.middlewares: 'authelia@docker'
  #     glance.name: Uptime Kuma
  #     glance.icon: /assets/uptimekuma.svg
  #     glance.url: https://kuma.${ROOT_FQDN}
  #     glance.description: Service Monitoring

  beszel:
    image: "henrygd/beszel:latest"
    container_name: "beszel"

    restart: unless-stopped
    # depends_on:
    #   - tailscale
    # network_mode: service:tailscale
    networks:
      - backbone-network
    volumes:
      - beszel_data:/beszel_data
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    # - 'gotify.${ROOT_FQDN}:${TRAEFIK_IP}'
    environment:
      TZ: ${TZ}
      LOG_LEVEL: debug
      USER_CREATION: true
    labels:
      meta.name: "beszel"
      meta.stack: ${STACK}
      traefik.enable: "true"
      traefik.http.services.beszel.loadbalancer.server.port: "8090"
      traefik.http.routers.beszel.rule: "Host(`beszel.${ROOT_FQDN}`)"
      traefik.http.routers.beszel.entrypoints: "websecure"
      traefik.http.routers.beszel.tls: "true"
      traefik.http.routers.beszel.service: "beszel"
      glance.name: Beszel
      glance.icon: /assets/beszel.svg
      glance.url: https://beszel.${ROOT_FQDN}
      glance.description: Infra Monitoring
      glance.id: beszel

  beszel-agent:
    image: "henrygd/beszel-agent:latest"
    container_name: "beszel-agent"
    hostname: ${HOSTNAME}
    restart: unless-stopped
    networks:
      - backbone-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: ${BESZEL_PUBLIC_KEY}
      LOG_LEVEL: debug
      TZ: ${TZ}
    labels:
      meta.name: "beszel-agent"
      meta.stack: ${STACK}
      glance.name: Beszel Agent
      glance.parent: beszel

  # quartz:
  #   image: shommey/dockerized-quartz
  #   container_name: quartz
  #   restart: unless-stopped
  #   networks:
  #   - backbone-network
  #   volumes:
  #   - ./obsidian-notes:/vault
  #   environment:
  #     TZ: ${TZ}
  #     REBUILD_WEBHOOK_SECRET: ${QUARTZ_REBUILD_WEBHOOK_SECRET}
  #     NOTIFY_TARGET: gotify://gotify/${GOTIFY_NOTIFY_TARGET}
  #     VAULT_DO_GIT_PULL_ON_UPDATE: true
  #   labels:
  #     meta.name: 'quartz'
  #     meta.stack: ${STACK}
  #     traefik.enable: 'true'
  #     traefik.http.services.quartz.loadbalancer.server.port: '80'
  #     traefik.http.routers.quartz.rule: 'Host(`quartz.${ROOT_FQDN}`)'
  #     traefik.http.routers.quartz.entrypoints: 'websecure'
  #     traefik.http.routers.quartz.tls: 'true'
  #     traefik.http.routers.quartz.service: 'quartz'
  #     traefik.http.routers.quartz.middlewares: 'authelia@docker'
  #     glance.name: Quartz
  #     glance.icon: /assets/obsidian.svg
  #     glance.url: https://quartz.${ROOT_FQDN}
  #     glance.description: Notes
