networks:
  backbone-network:
    name: ${STACK}
    attachable: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${ADMIN_NET_SUBNET}
          ip_range: ${ADMIN_NET_SUBNET}
          

volumes:
  tailscale_data:
  traefik_certs:
  beszel_data:
  postgres_data:


services:
  tailscale:
    image: tailscale/tailscale:v1.76.6
    container_name: tailscale
    hostname: traefik
    restart: unless-stopped
    networks:
    - backbone-network
    # ports:
      # - "80:80"
      # - "443:443"
      # - "8080:8080"
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      TZ: ${TZ}
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    labels:
      meta.name: 'tailscale'
      meta.stack: ${STACK}
      traefik.enable: 'true'
      traefik.http.routers.traefik.rule: 'Host(`traefik.${ROOT_FQDN}`) '
      traefik.http.routers.traefik.entrypoints: 'websecure'
      traefik.http.routers.traefik.service: 'api@internal'
      traefik.http.services.traefik.loadbalancer.server.port: '8080'
      traefik.http.routers.traefik.tls: 'true'
      traefik.http.routers.traefik.tls.certresolver: 'letsencrypt'
      traefik.http.routers.traefik.tls.domains[0].main: '$ROOT_FQDN'
      traefik.http.routers.traefik.tls.domains[0].sans: '*.$ROOT_FQDN'
      # Authelia
      traefik.http.routers.traefik.middlewares: 'authelia@docker'
      traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth'
      ## The following commented line is for configuring the Authelia URL in the proxy. We strongly suggest this is
      ## configured in the Session Cookies section of the Authelia configuration.
      # traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth?authelia_url=https%3A%2F%2Fauth.example.com%2F'
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Remote-User,Remote-Groups,Remote-Email,Remote-Name'

      traefik.http.services.beszel.loadbalancer.server.port: '8090'
      traefik.http.routers.beszel.rule: 'Host(`beszel.${ROOT_FQDN}`)'
      traefik.http.routers.beszel.entrypoints: 'websecure'
      traefik.http.routers.beszel.tls: 'true'
      traefik.http.routers.beszel.service: 'beszel'

      
  traefik:
    image: traefik:v3.2.3
    container_name: 'traefik'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - tailscale
    network_mode: service:tailscale

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - traefik_certs:/certs
      # - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
      # - ./traefik/acme.json:/acme.json
      # - ./traefik/traefik.log:/traefik.log
    environment:
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TZ: ${TZ}
    labels:
      meta.name: 'traefik'
      meta.stack: ${STACK}
      # traefik.enable: 'true'
      # traefik.http.routers.traefik.rule: 'Host(`traefik.${ROOT_FQDN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      # traefik.http.routers.traefik.entrypoints: 'websecure'
      # # traefik.http.routers.traefik.tls.certresolver: 'letsencrypt'
      # traefik.http.routers.traefik.service: 'api@internal'
      # traefik.http.services.traefik.loadbalancer.server.port: '8080'

      # Authelia
      # traefik.http.routers.api.middlewares: 'authelia@docker'
      # traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth'
      # ## The following commented line is for configuring the Authelia URL in the proxy. We strongly suggest this is
      # ## configured in the Session Cookies section of the Authelia configuration.
      # # traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth?authelia_url=https%3A%2F%2Fauth.example.com%2F'
      # traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      # traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Remote-User,Remote-Groups,Remote-Email,Remote-Name'

  postgres:
    image: postgres:16.3
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    container_name: 'postgres'
    restart: unless-stopped
    networks:
    - backbone-network
    volumes:
      - ./postgres/scripts/:/app/
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASS}
      TZ: ${TZ}
    # post_start:
    #   - command: cat /app/seed.sql | PGPASSWORD=${ADMIN_PASS} psql -h localhost -U ${ADMIN_USER} -d ${POSTGRES_DB} -f-
    # post_start:
    #   - command: cat /app/seed.sql | PGPASSWORD=${POSTGRES_PASSWORD} psql -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f-
    #     user: root
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${ADMIN_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    labels:
      meta.name: 'postgres'
      meta.stack: ${STACK}
      traefik.enable: 'true'
      traefik.tcp.services.postgres.loadbalancer.server.port: '5432'
      traefik.tcp.routers.postgres.rule: 'HostSNI(`postgres.${ROOT_FQDN}`)'
      traefik.tcp.routers.postgres.entrypoints: 'db'
      traefik.tcp.routers.postgres.tls: 'true'
      traefik.tcp.routers.postgres.tls.certresolver: 'letsencrypt'

  authelia:
    image: 'authelia/authelia:4.38'
    container_name: 'authelia'
    restart: unless-stopped
    user: "${UID}:${GID}"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    volumes:
      # - './authelia/secrets:/secrets:ro'
      - './authelia/config:/config'
      # - './authelia/logs:/var/log/authelia/'
    networks:
    - backbone-network 
    labels:
      ## Expose Authelia through Traefik
      meta.name: 'authelia'
      meta.stack: ${STACK}
      traefik.enable: 'true'
      traefik.http.services.auth.loadbalancer.server.port: '9091'
      traefik.http.routers.auth.rule: 'Host(`auth.${ROOT_FQDN}`)'
      traefik.http.routers.auth.entrypoints: 'websecure'
      traefik.http.routers.auth.tls: 'true'
      ## Setup Authelia ForwardAuth Middlewares
      # traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth'
      # traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      # traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    environment:
      TZ: ${TZ}
      X_AUTHELIA_CONFIG_FILTERS: 'template' 



     
  beszel:
    image: 'henrygd/beszel:latest' 
    container_name: 'beszel'
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale
    # networks:
    # - backbone-network
    volumes:
      - beszel_data:/beszel_data
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
      # - 'gotify.${ROOT_FQDN}:${TRAEFIK_IP}'
    environment:
      TZ: ${TZ}
      LOG_LEVEL: debug
      USER_CREATION: true
      # DISABLE_PASSWORD_AUTH: true
    labels:
      meta.name: 'beszel'
      meta.stack: ${STACK}
      # traefik.enable: 'true'
      # traefik.http.services.beszel.loadbalancer.server.port: '8090'
      # traefik.http.routers.beszel.rule: 'Host(`beszel.${ROOT_FQDN}`)'
      # traefik.http.routers.beszel.entrypoints: 'websecure'
      # traefik.http.routers.beszel.tls: 'true'
      # traefik.http.routers.beszel.middlewares: 'authelia@docker'

  beszel-agent:
    image: 'henrygd/beszel-agent:latest'
    container_name: 'beszel-agent'
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876 
      KEY: ${BESZEL_PUBLIC_KEY}
      LOG_LEVEL: debug
      TZ: ${TZ}
    labels:
      meta.name: 'beszel-agent'
      meta.stack: ${STACK}
  


