# traefik.yaml

api:
  insecure: false
  debug: true
  dashboard: true

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false

  # file:
  #   filename: /etc/traefik/dynamic_conf.yml
  #   watch: true

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      trustedIPs:
          - "127.0.0.1/32"
          - "192.168.1.7"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
          - "127.0.0.1/32"  #localhost
          - "10.0.0.0/8"    #home network   
          - "100.0.0.0/8"   #tailnet
          - "172.69.0.0/16" #admin-network

  db:
    address: ":5432"

# experimental:
#   plugins:
#     sablier:
#       moduleName: "github.com/sablierapp/sablier"
#       version: "v1.8.1"

accessLog:
  filePath: "/traefik.log"

certificatesResolvers:
  letsencrypt:
    acme:
      email: homeserver@kugel.homes
      storage: /certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # production (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10 #Optional to wait x second before checking with the DNS Server

