networks:
  backbone-network:
    name: ${BACKBONE_STACK}
    external: true
          

volumes:
  actual_data:
  gotify_data:
  hoarder_data:
  hoarder_meilisearch:
  jellyfin_config:
  jellyfin_cache:
  open_webui_data:
  firefly_data:



services:    
  # gotify:
  #   image: gotify/server:2.6.1
  #   container_name: 'gotify'
  #   restart: unless-stopped
  #   networks:
  #   - backbone-network
  #   volumes:
  #     - gotify_data:/app/data
  #     # - ./gotify/config.yml:/etc/gotify/config.yml
  #     # todo
  #   environment:
  #     # GOTIFY_DATABASE_DIALECT: postgres
  #     # GOTIFY_DATABASE_CONNECTION: ${GOTIFY_DATABASE_CONNECTION}
  #     GOTIFY_DEFAULTUSER_NAME: ${ADMIN_USER}
  #     GOTIFY_DEFAULTUSER_PASS: ${ADMIN_PASS}
  #     TZ: ${TZ}
  #   labels:
  #     meta.name: 'gotify'
  #     meta.stack: ${STACK}
  #     traefik.enable: 'true'
  #     traefik.http.services.gotify.loadbalancer.server.port: '80'
  #     traefik.http.routers.gotify.rule: 'Host(`gotify.${ROOT_FQDN}`)'
  #     traefik.http.routers.gotify.entrypoints: 'websecure'
  #     traefik.http.routers.gotify.tls: 'true'
 
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:0.22.0
    container_name: 'hoarder'
    restart: unless-stopped
    networks:
    - backbone-network
    volumes:
      - hoarder_data:/data
    environment:
      MEILI_ADDR: http://hoarder_meilisearch:7700
      BROWSER_WEB_URL: http://hoarder_chrome:9222
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      INFERENCE_IMAGE_MODEL: gpt-4o-mini
      INFERENCE_TEXT_MODEL: gpt-4o-mini
      DATA_DIR: /data
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      NEXTAUTH_URL: hoarder.${ROOT_FQDN}
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      DISABLE_PASSWORD_AUTH: true
      OAUTH_WELLKNOWN_URL: https://auth.${ROOT_FQDN}/.well-known/openid-configuration
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_PROVIDER_NAME: authelia
      TZ: ${TZ}
    labels:
      meta.name: 'hoarder'
      meta.stack: ${STACK}
      traefik.enable: 'true'
      traefik.http.services.hoarder.loadbalancer.server.port: '3000'
      traefik.http.routers.hoarder.rule: 'Host(`hoarder.${ROOT_FQDN}`)'
      traefik.http.routers.hoarder.entrypoints: 'websecure'
      traefik.http.routers.hoarder.tls: 'true'   
      # traefik.http.routers.hoarder.middlewares: 'authelia@docker'

  hoarder_chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: 'hoarder_chrome'
    restart: unless-stopped
    networks:
    - backbone-network
    environment:
      TZ: ${TZ}
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    labels:
      meta.name: 'hoarder_chrome'
      meta.stack: ${STACK}

  hoarder_meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: 'hoarder_meilisearch'
    restart: unless-stopped
    networks:
    - backbone-network
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      TZ: ${TZ}
    volumes:
      - hoarder_meilisearch:/meili_data
    labels:
      meta.name: 'hoarder_meilisearch'
      meta.stack: ${STACK}
  
  whoami:
    image: 'traefik/whoami'
    container_name: 'whoami'
    restart: 'unless-stopped'
    networks:
    - backbone-network    
    labels:
      meta.name: 'whoami'
      meta.stack: ${STACK}
      traefik.enable: 'true'
      traefik.http.services.whoami.loadbalancer.server.port: '80'
      traefik.http.routers.whoami.rule: 'Host(`whoami.${ROOT_FQDN}`)'
      traefik.http.routers.whoami.entrypoints: 'websecure'
      traefik.http.routers.whoami.tls: 'true'
      # traefik.http.routers.whoami.middlewares: 'authelia@docker'

  # jellyfin:
  #   image: jellyfin/jellyfin:10.10.3
  #   container_name: 'jellyfin'
  #   restart: unless-stopped
  #   networks:
  #   - backbone-network
  #   user: 1000:1000
  #   group_add:
  #     - "989"
  #   volumes:
  #     - "jellyfin_config:/config"
  #     - "jellyfin_cache:/cache"
  #     - "${MEDIA_DIRECTORY}:/media"
  #   devices:
  #     - /dev/dri/renderD128:/dev/dri/renderD128
  #     - /dev/dri/card1:/dev/dri/card0
  #   environment:
  #     - TZ=${TZ}
  #     # - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}  # Include protocol prefix (e.g. `https://)
  #     # - HEALTHCHECK_URL=http://localhost:80/health  # Change the server's jellyfleet port to 8096 here or to 80 in /config/config/network.xml
  #   labels:
  #     traefik.enable: 'true'
  #     traefik.http.services.jellyfin.loadbalancer.server.port: '8096'
  #     traefik.http.routers.jellyfin.rule: 'Host(`jellyfin.${ROOT_FQDN}`)'
  #     traefik.http.routers.jellyfin.entrypoints: 'websecure'
  #     traefik.http.routers.jellyfin.tls: 'true'

  # jellyseerr:
  #   image: fallenbagel/jellyseerr:latest
  #   container_name: 'jellyseerr'
  #   restart: unless-stopped
  #   networks:
  #   - backbone-network
  #   depends_on:
  #     jellyfin:
  #       condition: service_healthy
  #   environment:
  #     - LOG_LEVEL=${LOG_LEVEL}
  #     - TZ=${TZ}
  #   volumes:
  #     - "jellyseerr-config:/app/config"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
  #     - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.${ROOT_FQDN}`)"
  #     - "traefik.http.routers.jellyseerr.entrypoints=websecure"
  #     - "traefik.http.routers.jellyseerr.tls=true"
     
  open_webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: 'open_webui'
    restart: unless-stopped
    networks:
    - backbone-network
    volumes:
      - "open_webui_data:/app/backend/data"
    environment:
      TZ: ${TZ}
      WEBUI_URL: chat.${ROOT_FQDN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      ENABLE_OAUTH_SIGNUP: 'true'
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: 'true'
      OAUTH_CLIENT_ID: ${OPEN_WEBUI_OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OPEN_WEBUI_OAUTH_CLIENT_SECRET}
      OPENID_PROVIDER_URL: 'https://auth.kugel.homes/.well-known/openid-configuration'
      OAUTH_PROVIDER_NAME: 'Authelia'
      OAUTH_SCOPES: 'openid email profile groups'
      DEFAULT_USER_ROLE: user
      # ENABLE_OAUTH_ROLE_MANAGEMENT: 'true'
      # OAUTH_ALLOWED_ROLES: 'openwebui,openwebui-admin'
      # OAUTH_ADMIN_ROLES: 'openwebui-admin'
      # OAUTH_ROLES_CLAIM: 'groups'

    labels:
      traefik.enable: 'true'
      traefik.http.services.chat.loadbalancer.server.port: '8080'
      traefik.http.routers.chat.rule: 'Host(`chat.${ROOT_FQDN}`)'
      traefik.http.routers.chat.entrypoints: 'websecure'
      traefik.http.routers.chat.tls: 'true'

  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: unless-stopped
    networks:
    - backbone-network
    volumes:
      - firefly_data:/var/www/html/storage/upload
    environment:
      APP_ENV: production
      APP_DEBUG: false
      SITE_OWNER: ${ADMIN_EMAIL}
      APP_KEY: ${FIREFLY_APP_KEY}
      DEFAULT_LANGUAGE: en_US
      DEFAULT_LOCALE: equal
      TZ: ${TZ}
      TRUSTED_PROXIES: "**"
      LOG_CHANNEL: stack
      APP_LOG_LEVEL: notice
      AUDIT_LOG_LEVEL: emergency
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: firefly
      PGSQL_SSL_MODE: prefer
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      COOKIE_PATH: "/"
      COOKIE_SECURE: false
      COOKIE_SAMESITE: lax
      MAIL_MAILER: smtp
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: null
      SEND_ERROR_MESSAGE: true
      SEND_REPORT_JOURNALS: true
      AUTHENTICATION_GUARD: web
      AUTHENTICATION_GUARD_HEADER: HTTP_REMOTE_USER
      DISABLE_FRAME_HEADER: false
      DISABLE_CSP_HEADER: false
      ALLOW_WEBHOOKS: true
      APP_URL: https://firefly.${ROOT_FQDN}
    labels:
      traefik.enable: 'true'
      traefik.http.services.firefly.loadbalancer.server.port: '8080'
      traefik.http.routers.firefly.rule: 'Host(`firefly.${ROOT_FQDN}`)'
      traefik.http.routers.firefly.entrypoints: 'websecure'
      traefik.http.routers.firefly.tls: 'true'
      # traefik.http.routers.firefly.middlewares: 'authelia@docker'


  pico:
    image: cioraneanu/firefly-pico:latest
    container_name: pico
    restart: unless-stopped
    networks:
    - backbone-network
    volumes:
      - firefly_data:/var/www/html/storage/upload
    environment:
      FIREFLY_URL: http://firefly:8080
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: pico
      DB_USERNAME: pico
      DB_PASSWORD: pico
      TZ: ${TZ}
    labels:
      traefik.enable: 'true'
      traefik.http.services.pico.loadbalancer.server.port: '80'
      traefik.http.routers.pico.rule: 'Host(`pico.${ROOT_FQDN}`)'
      traefik.http.routers.pico.entrypoints: 'websecure'
      traefik.http.routers.pico.tls: 'true'
  
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    networks:
    - backbone-network
    environment:
      TZ: ${TZ}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file: glance.env
    volumes:
      - ./glance/config:/app/config
      - ./glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: 'true'
      traefik.http.services.glance.loadbalancer.server.port: '8080'
      traefik.http.routers.glance.rule: 'Host(`glance.${ROOT_FQDN}`)'
      traefik.http.routers.glance.entrypoints: 'websecure'
      traefik.http.routers.glance.tls: 'true'


